### ISSUE TITLE
actions: navigating while an action is inflight cuts off the Reactive System from reacting to new submission data

### ISSUE THREAD

**Issue by smrdotgg** [solidjs/solid-router#501] opened 2024-12-09 12:12 UTC
### Describe the bug

In SolidStart, if a navigation occurs while we have inflight actions/mutations/submissions, the reactive system is cut off from any updates on the state of the submission.

This can be demonstrated, and can present an issue on streams. Take for example a scenario where the user is on the URL /AI_CHAT/123 (where 123 is the ID of the ai chat). The LLM is streaming back data. if the user switches to /ai_chat/new or /ai_chat/124, then `useSubmissions` is suddenly cleared and the app is no longer aware of any streams happening, even though the stream is successfully coming through and can be observed in the network tab or in the console (if log statements are placed). 

This has been reproduced below. Feel free to take a look. 
Repo: https://github.com/smrdotgg/solid-action-bug
URL: https://solid-action-bug.vercel.app/

If you start a stream on the main page (in this reproduction, the server simply streams back counting 1-10), and navigate **_WHILE_** the navigation is occurring, the reactive system stops updating on new stream data. 

Having the submissions not be cleared could be useful for showing pending states in chat sidebars etc. (This was the use case I was looking for). 

@Brendonovich pointed out on Discord that this seems to be where the issue is arising from. I tried it out on a local build, and sure enough, it is. I even patched it locally, and everything is working fine, so you can be sure that this is what causes this behaviour.
![image](https://github.com/user-attachments/assets/e1f9ebbd-bbba-4956-80bd-d881b46d7ec3)
https://github.com/solidjs/solid-router/blob/main/src/routing.ts#L478

### Your Example Website or App

https://github.com/smrdotgg/solid-action-bug

### Steps to Reproduce the Bug or Issue

1. Open Page
2. Open your devtools. Keep an eye on your console.
3. Click "Count to 10" to start a server stream of numbers from 1 to 10
4. Before it hits 10, click to the "Other Page" in the nav bar
5. You will see that the UI stops responding to the new data eventhough new data is coming in as evidenced by the console logs

### Expected behavior

As a user, I expect the numbers in the shared route up above to keep updating even after the navigation as new data is coming in, however, they stop updating if I navigate before the stream finishes coming in.

### Platform

- OS: [Windows WSL]
- Browser: [e.g. Chrome]
- Version: [e.g. 131]

**Comment by ryansolid** [comment] 2024-12-09 17:27
Yeah this was an interesting choice. I wasn't sure if there were any impacts to this. My big concern was that submissions that error and aren't handled never clean up. My thinking that navigation was safe time to clean stuff up because the conceptual page navigation means new intent. Stuff like ErrorBoundaries automatically resetting happens in these sort of cases as well.

This particularly simplistic mind you and I can see why it would be a problem for in flight actions on parts of the page that aren't removed as part of the navigation. I wonder if there is a different approach we can take to preventing a slow memory leak here for actions that aren't handled. Because submissions are iterable I don't think a WeakSet would work.

**Comment by Brendonovich** [comment] 2024-12-09 17:47
Perhaps an action's submissions could be reference counted by how many `useSubmissions` are active, and when that hits 0 the submissions are removed from the list to be gc'd? Kinda weird but it'd be like having an iterable WeakSet

**Comment by smrdotgg** [comment] 2024-12-09 20:26
My two cents: I think the biggest problem here is the application state not reacting to streamed data specifically, or more broadly, to data crossing the network gap. Clearing all submissions per navigation makes sense in most cases. However, when data is being streamed, my immediate intuition is that any `effect` depending on that stream should run safely as long as the stream is active.

If the action is to be cleared, I think the corresponding browser-level network request should also be canceled to maintain a single true state.

Using reference counts could also work. However, I wonder if developers might find it confusing when `useSubmissions` returns an empty list in one route but a complete history in another. That can likely be addressed with clear documentation.

**Comment by ryansolid** [comment] 2024-12-10 21:58
Hmm.. maybe there is a simpler solution. Like only clear those that are done... That would work in your case atleast. Not sure it'd work for everyone but atleast it wouldn't mess with stuff that was ongoing.

**Comment by ryansolid** [comment] 2024-12-10 22:45
Ok I've looked at this now and I think we should make the change to not cancel inflight actions but on the other hand this example isn't really an `action`. In that it doesn't wait.. you can see that the final state logs before the stream even has started more or less. It completes before you ever navigate which means I don't think it is the routers responsibility. 

I tried my fix and I put the await back in and now it doesn't show the slow count but instead shows `loading...` but atleast it doesn't cancel on navigation. Generally speaking I don't know if the result of an action makes sense to be streamed in this manner. Like if it is streamed fine. But really if you wanted the stream to come in one number at a time it would be on the resource side.. the `query` side. An action might be like update something.. but count to 10 is very much a `GET`. All the effect/createSignal stuff would be replaced by `createAsync` which in Solid 2.0 will automatically handle ReadableStreams at which point you wouldn't be feeding it an action but rather just fetching what you needed perhaps with `query` if you needed to dedupe.

Honestly I don't even know if `action` makes sense if this has no impact on routing or data updating or whatnot but I'm gathering this is a simplified example of something else. So let me know if what I'm saying makes sense.

**Comment by smrdotgg** [comment] 2024-12-11 11:53
For my particular use case, I have applied a patch that I will talk about below.

You're right in that streaming really should be done on resources/`GET`'s. 

>`submissions[1](subs => subs.filter(s => s.pending));`
`pending` seems to be set to false as soon as the first chunk of data is received on the client (or more generally, if the promise returned by the function passed to `action` has resolved). If the function immediately returns a stream that then slowly sends down data, pending will quickly be set back to false (or might never be set to true if the action function doesn't wait on a network call to return a stream or a signal)

Filtering by the `pending` flag will still catch inflight actions (streamed or not) and that seems to be a plus I think. If `pending` is set to false on first chunk and we wanted to ensure streams don't get cut off on navigation, then we would need to somehow track the `pending|error|done` state of each stream, which would necessitate wrapping the `ReadableStream` to get these values etc etc. Its basically a giant hook, and I can't tell if that's all worth it or not. This may be something best left for `createAsync` in Solid 2.0.

For my use case in particular, I have a `ReadableStream` wrapper on the client that is returned from the actions that adds `& {__stream:{error: boolean; firstByteRecieved: boolean; done: boolean}}` to the payload. The navigator patch for `@solidjs/router` then checks if these flags are present, and if they are, it keeps all pending submissions and removes all the done and errored ones. This works for application code, but is probably not elegant and robust enough for a framework.


These are my thoughts. It might just be a good idea to leave streams for `resource`'s as well. I have something that works for my particular use case, but as for the router in general, I can't really tell if supporting streamed action responses is in good taste or not.

**Comment by ryansolid** [comment] 2024-12-11 22:26
Yeah the hardest part about async is understanding when it's done.. when we consider it consistent. The problem is as long it is not done you are still part of the transition. Still suspended etc.. So in that case it might as well be awaiting the last chunk because it is effectively the same. If you on the other hand consider it consistent or "done" with the first chunk then these primitives are done. So while an actions response could be streamed it is going to be either or. You decide whether to wait or not, but they need a definite finish and if you want something incremental well it isn't this that is doing it.

In the case of us doing singleflight mutations we say the action is done on the first chunk but use that as an opportunity to feed the returned promises into the query cache. And in so it streams directly into the query. The way I'm considering streams currently in 2.0 is that even for the GET side we are done with the first chunk, that's when Suspense lifts and loading states go away. The difference is the GET async resources are something are fixed on the page where actions are by their very nature ephemeral. 

In any case I've made my fix and I'm going consider this issue done for now.

**Closed by ryansolid** 2024-12-11 22:26 UTC
