### ISSUE TITLE
TypeScript checker error: Interface 'AnchorProps' incorrectly extends interface 'Omit<AnchorHTMLAttributes<HTMLAnchorElement>, "state">'

### ISSUE THREAD

**Issue by huseeiin** [solidjs/solid-router#302] opened 2023-10-04 16:10 UTC
### Describe the bug

```
node_modules/@solidjs/router/dist/components.d.ts:47:18 - error TS2430: Interface 'AnchorProps' incorrectly extends interface 'Omit<AnchorHTMLAttributes<HTMLAnchorElement>, "state">'.
  Types of property 'replace' are incompatible.
    Type 'boolean | undefined' is not assignable to type 'boolean'.
      Type 'undefined' is not assignable to type 'boolean'.

47 export interface AnchorProps extends Omit<JSX.AnchorHTMLAttributes<HTMLAnchorElement>, "state"> {
                    ~~~~~~~~~~~


Found 1 error in node_modules/@solidjs/router/dist/components.d.ts:47
```

### Your Example Website or App

https://github.com/xxxhussein/solidjs-reprod

### Steps to Reproduce the Bug or Issue

install @solidjs/router
run `tsc` without skipLibCheck: true

### Expected behavior

for the error to not occur

### Platform

- OS: [e.g. macOS, Windows, Linux]
- Browser: [e.g. Chrome, Safari, Firefox]
- Version: [e.g. 91.1]
OS: Windows 10
Browser: Brave
Version: 1.58.135

**Comment by femincan** [comment] 2023-12-20 20:52
I've tried but couldn't reproduce the issue. Everything seems working normally.

**Comment by ryansolid** [comment] 2024-01-31 00:06
reproduction seems to be gone now as well. Closing.

**Closed by ryansolid** 2024-01-31 00:06 UTC
Labels: pr welcome
